### ISSUE TITLE
Introspection - build 0.20.1

### ISSUE THREAD

**Issue by JTravis76** [lukemurray/EntityGraphQL#24] opened 2019-08-28 15:38 UTC
Ok, I’m bit confused here. Been testing against your latest build 0.20.1 and notice a few things related to Introspection.

## Missing INPUT_OBJECT kind:
In the BuildInputTypes method, there is a filter to get only IsInput. But I notice is set to true **ONLY** when using the AddInputType<>() method manually. 
How is the auto-generated mutation setting this flag?

```csharp
//SchemaIntrospection.cs
private static List<Models.TypeElement> BuildInputTypes(ISchemaProvider schema, IReadOnlyDictionary<Type, string> combinedMapping)
{
    var types = new List<Models.TypeElement>();

    foreach (ISchemaType schemaType in schema.GetNonContextTypes().Where(s => s.IsInput))
   {
       . . .
   }

//MappedSchemaProvider.cs
public SchemaType<TBaseType> AddInputType<TBaseType>(string name, string description)
{
    var tt = new SchemaType<TBaseType>(name, description, null, true);
     _types.Add(name, tt);
     return tt;
}
```

## Duplicating Kind/Type object 
The auto-generated mutation arguments has their kind/type repeating. The ofType is only need for `LIST` types. Doesn't seem to hurt anything, just bloat the JSON a bit.
Normal `OBJECT` types seem to be working as expected.
![Fig1](https://user-images.githubusercontent.com/9905282/63870047-35175400-c987-11e9-8a22-fac76bb38e8b.png)

Course if I comment out the `IsInput` filter that I mention above, it add INPUT_OBJECT types for *ALL* fields.

Example: the _Schema field was added twice.
For `INPUT_OBJECT`
*	fields should be empty array. Again, just bloat the JSON.
*	Cannot share the same name as an existing `OBJECT` types
*	TESTED: by changing the name to camelCase, worked for Introspection and Mutation queries

![Fig2](https://user-images.githubusercontent.com/9905282/63870048-35175400-c987-11e9-95cc-76325f11f8c8.png)

**Comment by lukemurray** [comment] 2019-08-29 06:39
@JTravis76 thanks.

First the auto generated mutation code doesn't currently auto-add complex types to the schema. _Currently_ if you have
```c#
public Expression<Db, Item> AddItem(Db ctx, MutationArgs args) { ... }

public MutationArgs
{
   public SomeClass { get; set; }
}
```
You currently need to call `schema.AddInputType<SomeClass>("GqlTypeNameForIt")`.

I agree this should be automattic at some point when using the `AddMutation()` method, like the demo does with the `Detail` class.

Am I miss understanding your question?

Regarding duplicating kind/type - thanks. Fixed in master. Also I believe the next `ofType` is required for `NON_NULL` types too, correct?

Yes if you change the code not to filter, it will add all the other types as input types. I see when using `AddInputType<>()` it is causing duplicate of that object. Fixed in master.

Question, int he demo example now it lists `Detail` as `INPUT_OBJECT` but in the `addMovie` mutation field is says 
```json
{
                  "name": "details",
                  "description": null,
                  "type": {
                    "kind": "LIST",
                    "name": null,
                    "ofType": {
                      "kind": "OBJECT",
                      "name": "Detail",
                      "ofType": null
                    }
                  },
                  "defaultValue": null
                }
```

I assume we need to make that say `INPUT_OBJECT` not `OBJECT`? GraphiQL doesn't mind.

Thanks again. Have a I missed anything?

**Comment by rkotenko** [comment] 2019-08-29 15:38
The latest master loads my schema fine in GraphiQL even when and input and object have the same name.  I am using the latest graphiql...cloned the repo and built it myself.

That being said, there is really no reason to have both.  If I define an object for input, it does not need to also exist as an OBJECT; it really is just kind of...there... since it is not included in the Query type

**Comment by JTravis76** [comment] 2019-08-29 17:47
@lukemurray I when through some extensive testing on the Introspection and I believe everything is working as expected. 
* I cleaned up the extra `INPUT_OBJECT` generated from MappedSchemaProvider
* Added the (3) base scalar types used by GraphiQL via the new CustomScalarType
* Remove `Subscription`, as there is no support yet

Since BuildType had a parameter isInput, I was able to use it by passing via the BuildMutationFields() (_since we know these are input type_) through the BuildArgs.

Attached are the updated files. No reason for a pull request.
Notice you commit recently, should be good, may compare just in-case :)

[0.20.0 Fixes.zip](https://github.com/lukemurray/EntityGraphQL/files/3556761/0.20.0.Fixes.zip)

**Comment by lukemurray** [comment] 2019-08-29 23:09
Thanks @JTravis76 

regarding the change in `Field.cs`
>//<-- JT - should we assist developers to force standards ???

I don't think we should force it. GQL spec says it is case sensitive and there clearly is a "ecosystem standard" but the spec doesn't say you can't name things `LiKe_This` etc. I do think when using the helper methods that derive the name like `AddField<TReturn>(Expression<Func<TBaseType, TReturn>> fieldSelection, string description, string returnSchemaType = null)` we should default to the "standard" which it currently does.

Also is `AddCustomScalarType(typeof(int), "Int");` and `String` and `Boolean required to be in the custom schema as they are defined as built in types for gql. Do you have errors without them?

**Comment by lukemurray** [comment] 2019-08-29 23:40
Thanks for noticing redundant code too!

**Comment by JTravis76** [comment] 2019-08-30 00:57
Understand completely on field naming, just thought I would bounce that off of you. 

As for the custom scalar, using the latest version of graphiql 13.2. They removed the default types _(int, string, and bool)_ from the app. That is one issue that Rob ran into. Included them just in case.

**Comment by lukemurray** [comment] 2019-08-30 04:00
Interesting. I updated graphiql in the demo via Nom and it is 0.14.x


________________________________

**Closed** 2019-08-30 12:09 UTC
