### ISSUE TITLE
 introspection issue with latest GraphiQL

### ISSUE THREAD

**Issue by rkotenko** [lukemurray/EntityGraphQL#21] opened 2019-07-28 17:22 UTC
According to #17, support for the introspection has been added.  I am running graphiql against my C# server.  I can query my tables. However, the initial query passed when graphiql loads, gives an error.  Seems to be a problem with 'fields.'  Here is a smaller query which returns the same error:

```javascript
{
  __type(name: "Application"){
    fields {
      name
    }
  }
}
```
And the error returned is

```
"Error compiling query 'fields'. Field 'fields' not found on current context '__Type'"
```

I am using a cloned version of master ( I had to downgrade some C# stuff because we use Framework 4.6.1, not Core). The 3rd newest commit on my repo is the merge for #17.

**Comment by lukemurray** [comment] 2019-07-29 00:17
My bad. I had published the nuget fix, but hadn't pushed the changes to github. Try now please.

**Comment by rkotenko** [comment] 2019-07-29 19:51
The code is there now.  However, the returned data seems to be missing Scalar types. GraphiQL gets returns 

```
Invalid or incomplete schema, unknown type: Int32...
```
when it tries to resolve type names.  I looked at graphql-dotnet and the types section of the return data starts like this before getting into data models:

```javascript
"types": [
        {
          "kind": "SCALAR",
          "name": "String",
          "description": null,
          "fields": null,
          "inputFields": null,
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": null
        },
        {
          "kind": "SCALAR",
          "name": "Boolean",
          "description": null,
          "fields": null,
          "inputFields": null,
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": null
        },
```
along with the rest of the scalar types.

In EntityGraphQL though, these do not appear except when referred to within the fields for my various data models.

In SchemaIntrospection.cs, I see where some types are added but does not include scalars:

```csharp
types.AddRange(BuildQueryTypes(schema, combinedMapping));
types.AddRange(BuildInputTypes(schema, combinedMapping));
types.AddRange(BuildEnumTypes(schema, combinedMapping));
```
The only reference though to scalars is when the args are built.

**Comment by JTravis76** [comment] 2019-07-29 22:32
@rkotenko thinking there is not a mapping for Int32, try using int instead. Let me know if helped

**Comment by lukemurray** [comment] 2019-07-29 23:40
Yes I think @JTravis76 is correct. I have pushed to master (not released yet) a change that maps Int32 (and others) to Int.

Let me know if that solves your problem. Using `int` as @JTravis76 said would work too, but we should map all the valid types.

**Comment by lukemurray** [comment] 2019-07-30 08:18
OK in the dictionary I can't add `typeof(Int32)` as it seems to clash with `typeof(int)` which makes sense to me, but weirdly I can't add `typeof(Int64)` as it claims it is already in the the dict. I have undone that quick change for now.

**Comment by rkotenko** [comment] 2019-07-30 12:58
I don't think Int32 is necessarily the issue.  In fact, I am not even sure where that came from.  It was misleading.  I still think the issue is with what is returned as I said above.

I ran it again and this is the error I get.

```
Error: Invalid or incomplete schema, unknown type: Int 
```

The exact error is occurring while trying to process args. Here are the args for my action (one of my tables) query:

```javascript
"args": [
              {
                "name": "id",
                "description": null,
                "type": {
                  "kind": "NON_NULL",
                  "name": null,
                  "ofType": {
                    "kind": "SCALAR",
                    "name": "Int",
                    "ofType": null
                  }
                },
                "defaultValue": null
              }
            ]
```

In graphiql, the type is passed into a function called getType.  When the kind is NON_NULL, it calls getType again with the 'ofType.'  There are 2 checks in getType: one for LIST and one for NON_NULL.  As the kind is SCALAR, it passes and calls getNamedType with ofType.name, which is Int.

 getNamedType uses a map, created using the returned types array, to find the type.  In that map is all of my tables as well as some graphql stuff like Query, Mutation, directives, etc.  What is not present though is a property for Int.  And this is because the types that come back do not include objects for scalars.

**Comment by rkotenko** [comment] 2019-07-30 13:08
As a quick test, I add Int as a type in SchemaIntrospection.cs

```csharp
var intType = new Models.TypeElement {
    Name = "Int",
    Kind = "SCALAR"
 };
types.Add(intType);
```

The error for Int no long occurs.  Now it is one for string:

```
Invalid or incomplete schema, unknown type: String
```

**Comment by rkotenko** [comment] 2019-07-30 14:50
I took a further look at the Int32 thing.  It occurs when dealing with a LIST

```CSharp
type.Kind = "LIST";
type.Name = null;
type.OfType = new Models.TypeElement
{
    Kind = "OBJECT",
    Name = isInput ? SchemaGenerator.ToCamelCaseStartsLower(field.ReturnTypeSingle) :field.ReturnTypeSingle
};

For singular fields, FindNamedMappings is called, but on LIST, it is just set to the ReturnType. Calling the mapping method would work for the final part of the ternary above, but it would not work for when it is an input since it is lowercased.  What is the reason for lowercasing the name here?

**Comment by JTravis76** [comment] 2019-07-30 15:48
@rkotenko Bit confuse what is throwing the error. Are you query the schema directly or this a mutation? Is this an args from a query? When using Graphiql, all basic scalar types are included. Built many complex entity objects and not seen that error. Also make me wonder if related to Framework.

Could you provide a small sample to review?

**Comment by rkotenko** [comment] 2019-07-30 16:08
This is the introspection result that comes back when graphiql first loads.  What is returned by EntityGraphQL does not include scalars in the types property.  It only has other Graphql details (__Directive, __EnumValues, etc) and the types for each entity.  I was able to fix the introspection by adding the scalar types of Int, String, and Boolean in SchemaIntrospection.cs.  Then I was able to fix the Int32 by calling FindNamedMappings with the element type of any list.  I did this in Make:

```CSharp
types.AddRange(BuildQueryTypes(schema, combinedMapping));
types.AddRange(BuildInputTypes(schema, combinedMapping));
types.AddRange(BuildEnumTypes(schema, combinedMapping));

// MY ADDED CODE
var scalarType = new Models.TypeElement {
    Name = "Int",
    Kind = "SCALAR"
};
           
types.Add(scalarType);

scalarType = new Models.TypeElement
{
    Name = "String",
    Kind = "SCALAR"
};

types.Add(scalarType);

scalarType = new Models.TypeElement
{
     Name = "Boolean",
     Kind = "SCALAR"
};

types.Add(scalarType);
```

and this in BuildType:

```CSharp
if (field.IsEnumerable)
{
    type.Kind = "LIST";
    type.Name = null;
    type.OfType = new Models.TypeElement
    {
        Kind = "OBJECT",
        // Resolve the element type instead of just setting the name to the array type
        Name = FindNamedMapping(field.ReturnTypeClr.GetElementType(), combinedMapping, field.ReturnTypeSingle)
    };
}
```
I removed the lowercasing for isInput so I don't know the effect there.  I have no mutations at the moment, so I can cross that bridge when I get there.

If I did not have an array in my model, I don't think this would be an issue.  Ironically, the field causing the problem is not even mapped to Entity; it is only used for special situations

**Comment by JTravis76** [comment] 2019-07-30 16:39
@rkotenko Okay, I finally able to reproduce. When using the latest CDN build of GraphiQL, it throws this error;

> Error: Invalid or incomplete schema, unknown type: Int. Ensure that a full introspection query is used in order to build a client schema.

```
https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.2/graphiql.js
https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.2/graphiql.css
```

Switching to version 0.13.0 worked without adding the built-in scalar types.

**Comment by rkotenko** [comment] 2019-07-30 16:59
Looks like I am using 0.13.2 (to be honest, I have been bouncing around version of it to get one working with our system so I lost track).  Must have been a change in 0.13.1 or maybe .2.

In any case, glad I am not crazy.  :)

What do you think about the Mapping thing though?  Int arrays type ofType names probably should resolve to the element Type not the string Int32, right?

**Comment by JTravis76** [comment] 2019-07-30 19:53
Workaround for GraphiQL 0.13.2 is to add the default _Types like so. Assuming it will be included in the next release.
```
public static MappedSchemaProvider<DataContext> MakeSchema()
{
    var schema = SchemaBuilder.FromObject<DataContext>();

    // Include default scalar types
    schema.AddType(typeof(int), "Int", null);
    schema.AddType(typeof(string), "String", null);
    schema.AddType(typeof(bool), "Boolean", null);

    …
}
```

As for Arrays of Long or Int, @lukemurray , I compare against an Array vs Collection and didn't know if there is a nice way to get the base type for `ReturnTypeSingle` of the array.

![GQL - Array types](https://user-images.githubusercontent.com/9905282/62160254-86c5b380-b2e1-11e9-9437-300583a6ea8b.png)

**Comment by rkotenko** [comment] 2019-07-30 20:52
What I did above for it gives you the type of array elements. It is a method of Type

```CSharp
field.ReturnTypeClr.GetElementType()
```

That method returns null if the  type is not an array.

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices._type.getelementtype?view=netframework-4.8#System_Runtime_InteropServices__Type_GetElementType

**Comment by lukemurray** [comment] 2019-08-02 09:44
@JTravis76 there is a helper extension method `GetEnumerableOrArrayType` to get the type of a `IEnumerable<>` or array.

Thanks for all the info @rkotenko I'll update GraphiQL and make the changes required

**Comment by lukemurray** [comment] 2019-08-27 22:08
@rkotenko `[ItemDetail]` looks like the correct result. Extra types in mutation arguments are not automatically added to the schema currently. You can add them like so:
`schemaProvider.AddInputType<ItemDetail>("ItemDetail", "Some description").AddAllFields();`

**Comment by lukemurray** [comment] 2019-08-27 22:18
@JTravis76 I see the issue that is fixed with `type.Kind = "LIST";` Thanks

**Comment by lukemurray** [comment] 2019-08-27 23:21
I realise there is an issue with List now. I am in the process of fixing it and making the introspection code more generic with how it builds Type information

**Comment by lukemurray** [comment] 2019-08-27 23:25
@rkotenko please check out current master, I pushed a fix for this. Also see the demo `addMovie` mutation where I added a example of using a `List<>`.

Let me know if you find any issue with this, if not I can push a release

**Comment by rkotenko** [comment] 2019-08-28 21:35
I dealt with this by making the argument its own class with the list inside it.  Which is really the recommended way to add input parameters anyway.

Even seems to be working well now.

**Comment by lukemurray** [comment] 2019-08-29 05:55
@rkotenko sorry, when you say "when I added `ItemInput` as a type" how did you do that?

And the last argument in the mutation should be a class that contains all the arguments for the mutation, This is hopefully semi clear in the readme (which I know is large)

**Comment by lukemurray** [comment] 2019-08-29 05:55
Ahh, I see you have it working now 👍

**Closed by lukemurray** 2019-08-29 05:55 UTC
